/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ProjectController;
import controllers.TaskController;
import models.Project;
import models.Task;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import util.ButtonColumnCellRenderer;
import util.DeadLineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author Héctor França
 */
public class MainFrame extends javax.swing.JFrame {

    private ProjectController projectController;
    private TaskController taskController;
    private DefaultListModel<Project> projectListModel;
    private TaskTableModel taskTableModel;

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() throws SQLException {
        initComponents();
        initDataControllers();
        initComponentsModel();

        decorateTaskTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTable = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelSlogan = new javax.swing.JLabel();
        jPanelProjects = new javax.swing.JPanel();
        jLabelProjects = new javax.swing.JLabel();
        jLabelAddProject = new javax.swing.JLabel();
        jPanelTasks = new javax.swing.JPanel();
        jLabelTasks = new javax.swing.JLabel();
        jLabelAddTask = new javax.swing.JLabel();
        jPanelProjectList = new javax.swing.JPanel();
        jScrollPaneProjectList = new javax.swing.JScrollPane();
        jListProjectList = new javax.swing.JList<>();
        jPanelTaskTable = new javax.swing.JPanel();
        jPanelEmptyTasks = new javax.swing.JPanel();
        jLabelEmptyTip = new javax.swing.JLabel();
        jLabelEmptyMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTableTasks.setAutoCreateRowSorter(true);
        jTableTasks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setFocusable(false);
        jTableTasks.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTasks.setRowHeight(50);
        jTableTasks.setSelectionBackground(new java.awt.Color(116, 69, 196));
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.setShowVerticalLines(false);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPaneTable.setViewportView(jTableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pacetask");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/logo.png")));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(600, 800));

        jPanelHeader.setBackground(new java.awt.Color(116, 69, 196));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Pacetask");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabelSlogan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelSlogan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSlogan.setText("Organize e gerencie suas tarefas");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addGap(18, 18, 18)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelSlogan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogo)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSlogan)
                        .addGap(6, 6, 6)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelProjects.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjects.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelProjects.setName(""); // NOI18N

        jLabelProjects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjects.setForeground(new java.awt.Color(116, 69, 196));
        jLabelProjects.setText("Projetos");

        jLabelAddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jLabelAddProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjectsLayout = new javax.swing.GroupLayout(jPanelProjects);
        jPanelProjects.setLayout(jPanelProjectsLayout);
        jPanelProjectsLayout.setHorizontalGroup(
            jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabelAddProject)
                .addContainerGap())
        );
        jPanelProjectsLayout.setVerticalGroup(
            jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjects)
                    .addComponent(jLabelAddProject))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTasks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTasks.setForeground(new java.awt.Color(116, 69, 196));
        jLabelTasks.setText("Tarefas");

        jLabelAddTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jLabelAddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTasksLayout = new javax.swing.GroupLayout(jPanelTasks);
        jPanelTasks.setLayout(jPanelTasksLayout);
        jPanelTasksLayout.setHorizontalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTasks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAddTask)
                .addContainerGap())
        );
        jPanelTasksLayout.setVerticalGroup(
            jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTasks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProjectList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPaneProjectList.setBorder(null);

        jListProjectList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jListProjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjectList.setFixedCellHeight(50);
        jListProjectList.setSelectionBackground(new java.awt.Color(116, 69, 196));
        jListProjectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjectListMouseClicked(evt);
            }
        });
        jScrollPaneProjectList.setViewportView(jListProjectList);

        javax.swing.GroupLayout jPanelProjectListLayout = new javax.swing.GroupLayout(jPanelProjectList);
        jPanelProjectList.setLayout(jPanelProjectListLayout);
        jPanelProjectListLayout.setHorizontalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelProjectListLayout.setVerticalGroup(
            jPanelProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjectListLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneProjectList))
        );

        jPanelTaskTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTaskTable.setLayout(new java.awt.BorderLayout());

        jPanelEmptyTasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmptyTasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEmptyTip.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEmptyTip.setForeground(new java.awt.Color(116, 69, 196));
        jLabelEmptyTip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyTip.setText("Clique no ícone \"+\" para adicionar uma tarefa");

        jLabelEmptyMessage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEmptyMessage.setForeground(new java.awt.Color(116, 69, 196));
        jLabelEmptyMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmptyMessage.setText("Não há tarefas cadastradas");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/404-error.png"))); // NOI18N

        javax.swing.GroupLayout jPanelEmptyTasksLayout = new javax.swing.GroupLayout(jPanelEmptyTasks);
        jPanelEmptyTasks.setLayout(jPanelEmptyTasksLayout);
        jPanelEmptyTasksLayout.setHorizontalGroup(
            jPanelEmptyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmptyTip, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addGroup(jPanelEmptyTasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelEmptyMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmptyTasksLayout.setVerticalGroup(
            jPanelEmptyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyTasksLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmptyMessage)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmptyTip)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelTaskTable.add(jPanelEmptyTasks, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTaskTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTaskTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddProjectMouseClicked
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, true);
        projectDialogScreen.setVisible(true);

        projectDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent event) {
                try {
                    loadProjects();
                    jListProjectList.setSelectedIndex(0);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_jLabelAddProjectMouseClicked

    private void jListProjectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjectListMouseClicked
        if (jListProjectList.getModel().getSize() > 0) {
            try {
                int projectIndex = jListProjectList.getSelectedIndex();
                Project project = (Project) projectListModel.get(projectIndex);

                loadTasks(project.getId());
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jListProjectListMouseClicked

    private void jLabelAddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddTaskMouseClicked
        if (!projectListModel.isEmpty()) {
            TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, true);

            int projectIndex = jListProjectList.getSelectedIndex();
            Project project = projectListModel.getElementAt(projectIndex);

            taskDialogScreen.setProject(project);
            taskDialogScreen.setVisible(true);

            taskDialogScreen.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent event) {
                    try {
                        loadTasks(project.getId());
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        }
    }//GEN-LAST:event_jLabelAddTaskMouseClicked

    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
        Task task = taskTableModel.getTasks().get(rowIndex);

        // Pegar o clique apenas no icone                
        if (jTableTasks.getColumnClass(columnIndex).equals(String.class)) {
            Component cellRendererComponent = jTableTasks.getCellRenderer(rowIndex, columnIndex).
                    getTableCellRendererComponent(
                            jTableTasks, task, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rowIndex, columnIndex);

            Rectangle cellRect = jTableTasks.getCellRect(rowIndex, columnIndex, true);
            cellRendererComponent.setLocation((int) cellRect.getCenterX() - 16, 10);

            if (cellRendererComponent.getBounds().contains(evt.getPoint())) {
                int projectIndex = jListProjectList.getSelectedIndex();
                Project project = projectListModel.getElementAt(projectIndex);

                switch (columnIndex) {
                    case 4:
                        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, true);

                        taskDialogScreen.setProject(project);
                        taskDialogScreen.setTask(task);
                        taskDialogScreen.setVisible(true);

                        taskDialogScreen.addWindowListener(new WindowAdapter() {
                            @Override
                            public void windowClosed(WindowEvent event) {
                                try {
                                    loadTasks(project.getId());
                                } catch (SQLException ex) {
                                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        });

                        break;
                    case 5:
                        int response = JOptionPane.showConfirmDialog(jTableTasks, "Deseja realmente excluir a tarefa?",
                                "Excluir Tarefa", 0);

                        if (response == 0) {
                            try {
                                taskController.removeById(task.getId());
                            } catch (SQLException ex) {
                                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            taskTableModel.getTasks().remove(task);

                            try {
                                loadTasks(project.getId());
                            } catch (SQLException ex) {
                                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }

                        break;
                }
            }
        } else if (columnIndex == 3) {
            try {
                taskController.update(task);
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTableTasksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainFrame.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddProject;
    private javax.swing.JLabel jLabelAddTask;
    private javax.swing.JLabel jLabelEmptyMessage;
    private javax.swing.JLabel jLabelEmptyTip;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelProjects;
    private javax.swing.JLabel jLabelSlogan;
    private javax.swing.JLabel jLabelTasks;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<Project> jListProjectList;
    private javax.swing.JPanel jPanelEmptyTasks;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelProjectList;
    private javax.swing.JPanel jPanelProjects;
    private javax.swing.JPanel jPanelTaskTable;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JScrollPane jScrollPaneProjectList;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

    public void initDataControllers() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    public void initComponentsModel() throws SQLException {
        projectListModel = new DefaultListModel<Project>();
        taskTableModel = new TaskTableModel();

        jListProjectList.setModel(projectListModel);
        jTableTasks.setModel(taskTableModel);

        loadProjects();

        if (!projectListModel.isEmpty()) {
            jListProjectList.setSelectedIndex(0);

            Project project = projectListModel.get(0);

            loadTasks(project.getId());
        }
    }

    public void loadProjects() throws SQLException {
        List<Project> projectsList = projectController.getAll();

        projectListModel.clear();

        for (Project project : projectsList) {
            projectListModel.addElement(project);
        }
    }

    public void loadTasks(int projectId) throws SQLException {
        List<Task> tasks = taskController.getAll(projectId);

        taskTableModel.setTasks(tasks);

        showTableTasks(!tasks.isEmpty());
    }

    public void decorateTaskTable() {
        jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTableTasks.getTableHeader().setBackground(new Color(116, 69, 196));
        jTableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
        jTableTasks.getTableHeader().setPreferredSize(new Dimension(100, 40));
        jTableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadLineColumnCellRenderer());
        jTableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
        jTableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
    }

    private void showTableTasks(boolean hasTasks) {
        if (hasTasks) {
            if (jPanelEmptyTasks.isVisible()) {
                jPanelEmptyTasks.setVisible(false);
                jPanelTaskTable.remove(jPanelEmptyTasks);
            }

            jPanelTaskTable.add(jScrollPaneTable);
            jScrollPaneTable.setVisible(true);
            jScrollPaneTable.setSize(
                    jPanelTaskTable.getWidth(), jPanelTaskTable.getHeight());

        } else {
            if (jScrollPaneTable.isVisible()) {
                jScrollPaneTable.setVisible(false);
                jPanelTaskTable.remove(jScrollPaneTable);
            }

            jPanelTaskTable.add(jPanelEmptyTasks);
            jPanelEmptyTasks.setVisible(true);
            jPanelEmptyTasks.setSize(
                    jPanelTaskTable.getWidth(), jPanelTaskTable.getHeight());
        }
    }
}
